nodes:
  # Wazuh indexer node
  indexer:
    - name: node-1
      ip: "<indexer-node-ip>" # ONLY CHANGE THIS VALUE

  # Wazuh server node
  server:
    - name: wazuh-1
      ip: "<wazuh-manager-ip>" # ONLY CHANGE THIS VALUE

  # Wazuh dashboard node
  dashboard:
    - name: dashboard
      ip: "<dashboard-node-ip>" # ONLY CHANGE THIS VALUE